import { Injectable } from '@angular/core';
import { HttpService } from './http.service';
import { HelperService } from './helper.service';
import * as location from 'countrycitystatejson';

@Injectable()
export class LocationService {

  constructor(public http: HttpService, public helper: HelperService) { }

  data: any = [
    {"language":"Afar","code":"AA"},
    {"language":"Abkhazian","code":"AB"},
    {"language":"Afrikaans","code":"AF"},
    {"language":"Akan","code":"AK"},
    {"language":"Amharic","code":"AM"},
    {"language":"Aragonese","code":"AN"},
    {"language":"Arabic","code":"AR"},
    {"language":"Assamese","code":"AS"},
    {"language":"Avar","code":"AV"},
    {"language":"Aymara","code":"AY"},
    {"language":"Azerbaijani","code":"AZ"},
    {"language":"Bashkir","code":"BA"},
    {"language":"Belarusian","code":"BE"},
    {"language":"Bulgarian","code":"BG"},
    {"language":"Bihari","code":"BH"},
    {"language":"Bislama","code":"BI"},
    {"language":"Bambara","code":"BM"},
    {"language":"Bengali","code":"BN"},
    {"language":"Tibetan","code":"BO"},
    {"language":"Breton","code":"BR"},
    {"language":"Bosnian","code":"BS"},
    {"language":"Catalan","code":"CA"},
    {"language":"Chechen","code":"CE"},
    {"language":"Chamorro","code":"CH"},
    {"language":"Corsican","code":"CO"},
    {"language":"Cree","code":"CR"},
    {"language":"Czech","code":"CS"},
    {"language":"Chuvash","code":"CV"},
    {"language":"Welsh","code":"CY"},
    {"language":"Danish","code":"DA"},
    {"language":"German","code":"DE"},
    {"language":"Divehi","code":"DV"},
    {"language":"Dzongkha","code":"DZ"},
    {"language":"Ewe","code":"EE"},
    {"language":"Greek","code":"EL"},
    {"language":"English","code":"EN"},
    {"language":"Esperanto","code":"EO"},
    {"language":"Spanish","code":"ES"},
    {"language":"Estonian","code":"ST"},
    {"language":"Basque","code":"EU"},
    {"language":"Persian","code":"FA"},
    {"language":"Peul","code":"FF"},
    {"language":"Finnish","code":"FI"},
    {"language":"Fijian","code":"FJ"},
    {"language":"Faroese","code":"FO"},
    {"language":"French","code":"FR"},
    {"language":"West Frisian","code":"FY"},
    {"language":"Irish","code":"GA"},
    {"language":"Scottish Gaelic","code":"GD"},
    {"language":"Galician","code":"GL"},
    {"language":"Guarani","code":"GN"},
    {"language":"Gujarati","code":"GU"},
    {"language":"Manx","code":"GV"},
    {"language":"Hausa","code":"HA"},
    {"language":"Hebrew","code":"HE"},
    {"language":"Hindi","code":"HI"},
    {"language":"Hiri Motu","code":"HO"},
    {"language":"Croatian","code":"HR"},
    {"language":"Haitian","code":"HT"},
    {"language":"Hungarian","code":"HU"},
    {"language":"Armenian","code":"HY"},
    {"language":"Herero","code":"HZ"},
    {"language":"Interlingua","code":"IA"},
    {"language":"Indonesian","code":"ID"},
    {"language":"Interlingue","code":"IE"},
    {"language":"Igbo","code":"IG"},
    {"language":"Sichuan Yi","code":"II"},
    {"language":"Inupiak","code":"IK"},
    {"language":"Ido","code":"IO"},
    {"language":"Icelandic","code":"IS"},
    {"language":"Italian","code":"IT"},
    {"language":"Inuktitut","code":"IU"},
    {"language":"Japanese","code":"JA"},
    {"language":"Javanese","code":"JV"},
    {"language":"Kongo","code":"KG"},
    {"language":"Kikuyu","code":"KI"},
    {"language":"Kuanyama","code":"KJ"},
    {"language":"Kazakh","code":"KK"},
    {"language":"Greenlandic","code":"KL"},
    {"language":"Cambodian","code":"KM"},
    {"language":"Kannada","code":"KM"},
    {"language":"Korean","code":"KO"},
    {"language":"Kanuri","code":"KR"},
    {"language":"Kashmiri","code":"KS"},
    {"language":"Kurdish","code":"KU"},
    {"language":"Komi","code":"KV"},
    {"language":"Cornish","code":"KW"},
    {"language":"Kirghiz","code":"KY"},
    {"language":"Latin","code":"LA"},
    {"language":"Luxembourgish","code":"LB"},
    {"language":"Ganda","code":"LG"},
    {"language":"Limburgian","code":"LI"},
    {"language":"Lingala","code":"LN"},
    {"language":"Laotian","code":"LO"},
    {"language":"Lithuanian","code":"LT"},
    {"language":"Latvian","code":"LV"},
    {"language":"Malagasy","code":"MG"},
    {"language":"Marshallese","code":"MH"},
    {"language":"Maori","code":"MI"},
    {"language":"Macedonian","code":"MK"},
    {"language":"Malayalam","code":"ML"},
    {"language":"Mongolian","code":"MN"},
    {"language":"Moldovan","code":"MO"},
    {"language":"Marathi","code":"MR"},
    {"language":"Malay","code":"MS"},
    {"language":"Maltese","code":"MT"},
    {"language":"Burmese","code":"MY"},
    {"language":"Nauruan","code":"NA"},
    {"language":"North Ndebele","code":"ND"},
    {"language":"Nepali","code":"NE"},
    {"language":"Ndonga","code":"NG"},
    {"language":"Dutch","code":"NL"},
    {"language":"Norwegian Nynorsk","code":"NN"},
    {"language":"Norwegian","code":"NO"},
    {"language":"South Ndebele","code":"NR"},
    {"language":"Navajo","code":"NV"},
    {"language":"Chichewa","code":"NY"},
    {"language":"Occitan","code":"OC"},
    {"language":"Ojibwa","code":"OJ"},
    {"language":"Oromo","code":"OM"},
    {"language":"Oriya","code":"OR"},
    {"language":"Ossetian","code":"OS"},
    {"language":"Punjabi","code":"PA"},
    {"language":"Pali","code":"PI"},
    {"language":"Polish","code":"PL"},
    {"language":"Pashto","code":"PS"},
    {"language":"Portuguese","code":"PT"},
    {"language":"Quechua","code":"QU"},
    {"language":"Raeto Romance","code":"RM"},
    {"language":"Kirundi","code":"RN"},
    {"language":"Romanian","code":"RO"},
    {"language":"Russian","code":"RU"},
    {"language":"Rwandi","code":"RW"},
    {"language":"Sanskrit","code":"SA"},
    {"language":"Sardinian","code":"SC"},
    {"language":"Sindhi","code":"SD"},
    {"language":"Sango","code":"SG"},
    {"language":"Serbo-Croatian","code":"SH"},
    {"language":"Sinhalese","code":"SI"},
    {"language":"Slovak","code":"SK"},
    {"language":"Slovenian","code":"SL"},
    {"language":"Samoan","code":"SM"},
    {"language":"Shona","code":"SN"},
    {"language":"Somalia","code":"SO"},
    {"language":"Albanian","code":"SQ"},
    {"language":"Serbian","code":"SR"},
    {"language":"Swati","code":"SS"},
    {"language":"Southern Sotho","code":"ST"},
    {"language":"Sundanese","code":"SU"},
    {"language":"Swedish","code":"SV"},
    {"language":"Swahili","code":"SW"},
    {"language":"Tamil","code":"TA"},
    {"language":"Telugu","code":"TE"},
    {"language":"Tajik","code":"TG"},
    {"language":"Thai","code":"TH"},
    {"language":"Tigrinya","code":"TI"},
    {"language":"Turkmen","code":"TK"},
    {"language":"Tagalog","code":"TL"},
    {"language":"Tswana","code":"TN"},
    {"language":"Tonga","code":"TO"},
    {"language":"Turkish","code":"TR"},
    {"language":"Tsonga","code":"TS"},
    {"language":"Tatar","code":"TT"},
    {"language":"Twi","code":"TW"},
    {"language":"Tahitian","code":"TY"},
    {"language":"Uyghur","code":"UG"},
    {"language":"Urdu","code":"UR"},
    {"language":"Venda","code":"VE"},
    {"language":"Vietnamese","code":"VI"},
    {"language":"Volapük","code":"VO"},
    {"language":"Walloon","code":"WA"},
    {"language":"Wolof","code":"WO"},
    {"language":"Xhosa","code":"XH"},
    {"language":"Yiddish","code":"YI"},
    {"language":"Yoruba","code":"YO"},
    {"language":"Zhuang","code":"ZA"},
    {"language":"Chinese","code":"ZH"},
    {"language":"Zulu","code":"ZU"}
  ];
  

  getCountriesList() {
    let stringArray = location.getCountries().sort((a, b) => a.name - b.name);
    var sortedArray: string[] = stringArray.sort((n1,n2) => {
      if (n1.name > n2.name) { return 1; }  
      if (n1.name < n2.name) { return -1; }  
      return 0;
    });
    return  sortedArray as any[];
  }
  getStatesList(country: string) {
    return location.getStatesByShort(country) as any[];
  }
  getCitiesList(country: string, state: string) {
    return location.getCities(country, state) as any[];
  }
  getCurrency(): Promise<any[]> {
    return this.http.get(`https://openexchangerates.org/api/latest.json?app_id=ad03a6b8893a48cea5dcbb3886129cde`)
      .then(response => response as any[])
      .catch(this.helper.handleError);
  }
  getLanguagesList(){
    return  this.data as any[];
  }

}